BUTTON_HEIGHT = 40
BUTTON_WIDTH = 100
UPLOAD_BUTTON_WIDTH = 150
LISTBOX_WIDTH = 150
DRAGO = " Drago "
REINHARD = " Reinhard "
LDR_CONTAINER = "ldr_container"
GENERATED_CONTAINER = "generated_container"
UPLOAD_LDR_DIALOG = "upload_ldr_dialog"
SAVE_FILE_DIALOG = "save_file_dialog"
GENERATE_BUTTON = "generate_button"
SAVE_BUTTON = "save_button"
ORIGINAL_LDR_IMAGE = "original_ldr"
GENERATED_IMAGE = "generated"
LDR_REGISTRY = "ldr_registry"
GENERATED_REGISTRY = "generated_registry"
PROGRESS_GROUP = "progress_group"
PROGRESS_BAR = "progress_bar"
ERROR_MODAL = "error_modal"
ERROR_MESSAGE = "error_message"
SAVE_MODAL = "save_modal"